Repository pulumi/pulumi-java, pull requests merged in 2022-07, with the labels that each got.

#723 Use local version of SDK when make test_example.minimal
  tests/examples/minimal/pom.xml
Labels: impact/no-changelog-required

#724 Update rewriteconversions api to match branch on pulumi/pulumi
  pkg/codegen/java/gen_program_expressions.go
  pkg/codegen/java/gen_test.go
  pkg/go.mod
  pkg/go.sum
Labels: impact/no-changelog-required

#722 Revert "Pin Pulumi CLI to working version (#684)"
  .github/workflows/pr.yml
Labels: impact/no-changelog-required

#741 Clean provider management make targets
  Makefile
  scripts/providers-generate-all.sh
  scripts/providers-install-all.sh
Labels: impact/no-changelog-required

#746 Don't panic during program-gen
  pkg/codegen/java/gen_program.go
  pkg/codegen/java/gen_program_expressions.go
Labels: impact/no-changelog-required, area/codegen

#745 Use program gen test framework
  pkg/codegen/java/gen_program.go
  pkg/codegen/java/gen_program_test.go
  pkg/codegen/testing/test/testdata/aws-eks-pp/java/aws-eks.java
  pkg/codegen/testing/test/testdata/aws-eks.pp
  pkg/codegen/testing/test/testdata/aws-fargate-pp/aws-fargate.pp
  pkg/codegen/testing/test/testdata/aws-fargate-pp/java/aws-fargate.java
  pkg/codegen/testing/test/testdata/aws-s3-folder-pp/aws-s3-folder.pp
  pkg/codegen/testing/test/testdata/aws-s3-folder-pp/java/aws-s3-folder.java
  pkg/codegen/testing/test/testdata/aws-s3-logging-pp/aws-s3-logging.pp
  pkg/codegen/testing/test/testdata/aws-s3-logging-pp/java/aws-s3-logging.java
  pkg/codegen/testing/test/testdata/aws-webserver-pp/aws-webserver.pp
  pkg/codegen/testing/test/testdata/aws-webserver-pp/java/aws-webserver.java
  pkg/codegen/testing/test/testdata/azure-native-pp/azure-native.pp
  pkg/codegen/testing/test/testdata/azure-native-pp/java/azure-native.java
  pkg/codegen/testing/test/testdata/azure-sa-pp/azure-sa.pp
  pkg/codegen/testing/test/testdata/azure-sa-pp/java/azure-sa.java
  pkg/codegen/testing/test/testdata/kubernetes-operator-pp/java/kubernetes-operator.java
  pkg/codegen/testing/test/testdata/kubernetes-operator-pp/kubernetes-operator.pp
  pkg/codegen/testing/test/testdata/kubernetes-pod-pp/java/kubernetes-pod.java
  pkg/codegen/testing/test/testdata/kubernetes-pod-pp/kubernetes-pod.pp
  pkg/codegen/testing/test/testdata/kubernetes-template-pp/java/kubernetes-template.java
  pkg/codegen/testing/test/testdata/kubernetes-template-pp/kubernetes-template.pp
  pkg/codegen/testing/test/testdata/output-funcs-aws-pp/java/output-funcs-aws.java
  pkg/codegen/testing/test/testdata/output-funcs-aws-pp/output-funcs-aws.pp
  pkg/codegen/testing/test/testdata/random-pet-pp/java/random-pet.java
  pkg/codegen/testing/test/testdata/random-pet-pp/random-pet.pp
  pkg/codegen/testing/test/testdata/resource-options-pp/java/resource-options.java
  pkg/codegen/testing/test/testdata/resource-options-pp/resource-options.pp
  pkg/codegen/testing/test/testdata/secret-pp/java/secret.java
  pkg/codegen/testing/test/testdata/secret-pp/secret.pp
  pkg/codegen/testing/test/testdata/simple-invoke-with-range-pp/java/simple-invoke-with-range.java
  pkg/codegen/testing/test/testdata/simple-invoke-with-range-pp/simple-invoke-with-range.pp
Labels: impact/no-changelog-required, area/testing

#752 Delete deprecated and unused code
  pkg/cmd/pulumi-java-gen/generate.go
  pkg/cmd/pulumi-java-gen/main.go
  pkg/cmd/pulumi-java-gen/old.go
  pkg/cmd/pulumi-java-gen/overlay.go
Labels: impact/no-changelog-required

#758 Fix default package references
  pkg/cmd/pulumi-java-gen/command.go
  pkg/codegen/java/gen_test.go
  pkg/codegen/java/package_info.go
  pkg/codegen/java/templates_gradle.go
  pkg/codegen/testing/test/testdata/azure-native-nested-types/java/build.gradle
  pkg/codegen/testing/test/testdata/cyclic-types/java/build.gradle
  pkg/codegen/testing/test/testdata/dash-named-schema/java/build.gradle
  pkg/codegen/testing/test/testdata/dashed-import-schema/java/build.gradle
  pkg/codegen/testing/test/testdata/jumbo-resources/java/build.gradle
  pkg/codegen/testing/test/testdata/mini-awsclassic/java/build.gradle
  pkg/codegen/testing/test/testdata/mini-awsnative/java/build.gradle
  pkg/codegen/testing/test/testdata/mini-awsx/java/build.gradle
  pkg/codegen/testing/test/testdata/mini-azuread/java/build.gradle
  pkg/codegen/testing/test/testdata/mini-azurenative/java/build.gradle
  pkg/codegen/testing/test/testdata/mini-kubernetes/java/build.gradle
  pkg/codegen/testing/test/testdata/naming-collisions/java/build.gradle
  pkg/codegen/testing/test/testdata/nested-module-thirdparty/java/build.gradle
  pkg/codegen/testing/test/testdata/nested-module/java/build.gradle
  pkg/codegen/testing/test/testdata/other-owned/java/build.gradle
  pkg/codegen/testing/test/testdata/output-funcs-edgeorder/java/build.gradle
  pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/java/build.gradle
  pkg/codegen/testing/test/testdata/output-funcs/java/build.gradle
  pkg/codegen/testing/test/testdata/plain-and-default/java/build.gradle
  pkg/codegen/testing/test/testdata/replace-on-change/java/build.gradle
  pkg/codegen/testing/test/testdata/resource-args-python-case-insensitive/java/build.gradle
  pkg/codegen/testing/test/testdata/resource-args-python/java/build.gradle
  pkg/codegen/testing/test/testdata/resource-property-overlap/java/build.gradle
  pkg/codegen/testing/test/testdata/simple-enum-schema/java/build.gradle
  pkg/codegen/testing/test/testdata/simple-plain-schema-with-root-package/java/build.gradle
  pkg/codegen/testing/test/testdata/simple-plain-schema/java/build.gradle
  pkg/codegen/testing/test/testdata/simple-resource-schema-custom-pypackage-name/java/build.gradle
  pkg/codegen/testing/test/testdata/simple-resource-schema/java/build.gradle
  pkg/codegen/testing/test/testdata/simple-yaml-schema/java/build.gradle
Labels: impact/no-changelog-required
